### ISSUE TITLE
`[1] XXXX killed pinata-cli -s ...` Error killing process

### ISSUE THREAD

**Issue by oznekenzo** [polluterofminds/pinata-cli#3] opened 2022-04-07 20:58 UTC
Hello,

Thanks for this util! 
I'm trying to upload a folder with 10,000 pngs worth 22GB (you guessed it, NFTs), but keep running up against the errors:

```
[1]    6301 killed     pinata-cli -s ./path/to/folder
```

Each time, the number, here as 6301, does increase - wondering if running this function is working its way to all 10,000 files incrementally, even with the killed processes?

Uploading through the browser was of course not working very well, and this was my only recourse.
Wondering if there's something I can do to get these files submarined and uploaded?

Thanks for all your work on this.

**Comment by polluterofminds** [comment] 2022-04-07 21:17
Hey @oznekenzo we (the Pinata team) is aware of some issue with large folders being uploaded to the Submarine API. Are you getting this error after getting to the point where the CLI output says: 

> Finishing processing, please wait...

**Comment by oznekenzo** [comment] 2022-04-07 21:35
No, have not been seeing this output 🙏

**Comment by oznekenzo** [comment] 2022-04-13 12:03
Wondering whether I could be expecting a solve for this in the next week or two? If not, I'll upload without submarining after the reveal - but the submarine feature would be great to get that out of the way before hand! Thanks again

**Comment by Blackening999** [comment] 2022-04-14 20:20
The same issue too. Kind of killing the whole idea of using Pinata :( Other methods don't work. My collection even larger!

**Comment by polluterofminds** [comment] 2022-04-14 20:47
Hey all, this is unlikely to be solved in the next week or two. I don't recommend using the submarine functionality for NFT reveals. It's really not a great use case at this point. Submarine is great for exposing people to additional content based on ownership of existing NFTs as opposed to doing a reveal for your drop. 

@Blackening999 can you confirm you're seeing this when running the upload to submarine command as opposed to the regular upload command?

**Comment by polluterofminds** [comment] 2022-06-01 18:45
Large uploads to the submarine API is an issue tracked by our engineering team but is not a bug with this CLI. Closing this issue unless additional information arises suggesting it should be re-opened.

**Closed as completed by polluterofminds** 2022-06-01 18:45 UTC
